### ISSUE TITLE
[1.20.1] Tick loop Crash when opening chest / fighting entity

### ISSUE THREAD

**Issue by MrKashew** [CursedFlames/Modifiers#10]
[crash-2023-07-11_14.12.41-server.txt](https://github.com/CursedFlames/Modifiers/files/12021787/crash-2023-07-11_14.12.41-server.txt)
[crash-2023-07-11_14.53.04-server.txt](https://github.com/CursedFlames/Modifiers/files/12021788/crash-2023-07-11_14.53.04-server.txt)

**Comment by CursedFlames** [comment]
This looks unrelated to Modifiers? `Modifiers` doesn't appear anywhere except the mod list at the end.

Can you test whether this crash still happens without Modifiers present? if so, this isn't a Modifiers issue, otherwise please try to find the specific mods that crash alongside Modifiers.

**Comment by MrKashew** [comment]
Sorry for vagueness, yes it crashes with modifiers and crash is gone once I remove it 👀

**Comment by MrKashew** [comment]
upon further investigation it is an incompatibility with an old version of Iron's Spellbooks mod, it has been fixed on that mod!
